- hosts: webservers
  become: true
  tasks: 
  - name: install apache2
    apt:
     name: apache2
     state: present
  - name: checking apache status 
    service: 
     name: apache2 
     state: started     
    