- hosts: webservers
  become: true
  tasks:
  - name: install nginx
    apt:
     name: nginx
     state: present

  - name: checking nginx status
    service:
     name: nginx
     state: started
  - name: install ngninx
    apt:
     name: nginx
     state: present

  - name: checking nginx status
    service:
     name: nginx
     state: started