- hosts: webservers
  become: true
  vars:
   admin: pkadmin
   software: apache2
   ownername: tk
  tasks:
  - name: Create group
    group:
     name: "{{ admin }}"
     gid: 401 #meaning group id
      
  - name: create user
    user:
     name: "{{ ownername }}"
     state: present
     uid: 400      #meaning user id
     groups: "{{ admin }}" #meaning you have to create group first
     shell: /bin/bash

  - name: create  file
    file:
     path: /opt/webconfig.conf
     state: touch
     owner: "{{ ownername }}" #meaning you have to create user and group first
     group: "{{ admin }}"

  - name: Creating folder
    file:
     path: /opt/webfile
     state: directory
     owner: "{{ ownername }}" 
     group: "{{ admin }}"
     # add other task to waht we have  already installing apache and doanloading some files from the intenrt
  - name: install apache2 and download the files
    apt:
     name: "{{ software }}"
     state: present

  - name: start the apache2 service
    service:
     name: "{{ software }}"
     state: started
     enabled: yes
