- hosts: webservers
  become: true
  vars:
   software: nginx
  tasks:
  - name: install nginx
    apt:
     name: "{{ software }}"
     state: present

  - name: checking nginx status
    service:
     name: "{{ software }}"
     state: started
  - name: install ngninx
    apt:
     name: "{{ software }}"
     state: present
